export const artist_countries_codes_currency = [
  {
    name: "Andorra",
    alpha2: "AD",
    alpha3: "AND",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Austria",
    alpha2: "AT",
    alpha3: "AUT",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Belgium",
    alpha2: "BE",
    alpha3: "BEL",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Benin",
    alpha2: "BJ",
    alpha3: "BEN",
    currency: "XOF",
    symbol: "CFA",
  },
  {
    name: "Botswana",
    alpha2: "BW",
    alpha3: "BWA",
    currency: "BWP",
    symbol: "P",
  },
  {
    name: "Bulgaria",
    alpha2: "BG",
    alpha3: "BGR",
    currency: "BGN",
    symbol: "лв",
  },
  {
    name: "Cameroon",
    alpha2: "CM",
    alpha3: "CMR",
    currency: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    currency: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Chad",
    alpha2: "TD",
    alpha3: "TCD",
    currency: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Côte d'Ivoire",
    alpha2: "CI",
    alpha3: "CIV",
    currency: "XOF",
    symbol: "CFA",
  },
  {
    name: "Croatia",
    alpha2: "HR",
    alpha3: "HRV",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Cyprus",
    alpha2: "CY",
    alpha3: "CYP",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Czech Republic",
    alpha2: "CZ",
    alpha3: "CZE",
    currency: "CZK",
    symbol: "Kč",
  },
  {
    name: "Denmark",
    alpha2: "DK",
    alpha3: "DNK",
    currency: "DKK",
    symbol: "kr",
  },
  { name: "Egypt", alpha2: "EG", alpha3: "EGY", currency: "EGP", symbol: "£" },
  {
    name: "Estonia",
    alpha2: "EE",
    alpha3: "EST",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Ethiopia",
    alpha2: "ET",
    alpha3: "ETH",
    currency: "ETB",
    symbol: "Br",
  },
  {
    name: "Finland",
    alpha2: "FI",
    alpha3: "FIN",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "France",
    alpha2: "FR",
    alpha3: "FRA",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Gabon",
    alpha2: "GA",
    alpha3: "GAB",
    currency: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Germany",
    alpha2: "DE",
    alpha3: "DEU",
    currency: "EUR",
    symbol: "€",
  },
  { name: "Ghana", alpha2: "GH", alpha3: "GHA", currency: "GHS", symbol: "₵" },
  {
    name: "Greece",
    alpha2: "GR",
    alpha3: "GRC",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Hungary",
    alpha2: "HU",
    alpha3: "HUN",
    currency: "HUF",
    symbol: "Ft",
  },
  {
    name: "Iceland",
    alpha2: "IS",
    alpha3: "ISL",
    currency: "ISK",
    symbol: "kr",
  },
  {
    name: "Ireland",
    alpha2: "IE",
    alpha3: "IRL",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Italy",
    alpha2: "IT",
    alpha3: "ITA",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Kenya",
    alpha2: "KE",
    alpha3: "KEN",
    currency: "KES",
    symbol: "KSh",
  },
  {
    name: "Latvia",
    alpha2: "LV",
    alpha3: "LVA",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Liechtenstein",
    alpha2: "LI",
    alpha3: "LIE",
    currency: "CHF",
    symbol: "CHF",
  },
  {
    name: "Lithuania",
    alpha2: "LT",
    alpha3: "LTU",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Luxembourg",
    alpha2: "LU",
    alpha3: "LUX",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Malawi",
    alpha2: "MW",
    alpha3: "MWI",
    currency: "MWK",
    symbol: "MK",
  },
  {
    name: "Malta",
    alpha2: "MT",
    alpha3: "MLT",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Monaco",
    alpha2: "MC",
    alpha3: "MCO",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Netherlands",
    alpha2: "NL",
    alpha3: "NLD",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Nigeria",
    alpha2: "NG",
    alpha3: "NGA",
    currency: "NGN",
    symbol: "₦",
  },
  {
    name: "Norway",
    alpha2: "NO",
    alpha3: "NOR",
    currency: "NOK",
    symbol: "kr",
  },
  {
    name: "Poland",
    alpha2: "PL",
    alpha3: "POL",
    currency: "PLN",
    symbol: "zł",
  },
  {
    name: "Portugal",
    alpha2: "PT",
    alpha3: "PRT",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Republic of Congo",
    alpha2: "CG",
    alpha3: "COG",
    currency: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Romania",
    alpha2: "RO",
    alpha3: "ROU",
    currency: "RON",
    symbol: "lei",
  },
  {
    name: "Rwanda",
    alpha2: "RW",
    alpha3: "RWA",
    currency: "RWF",
    symbol: "FRw",
  },
  {
    name: "San Marino",
    alpha2: "SM",
    alpha3: "SMR",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Senegal",
    alpha2: "SN",
    alpha3: "SEN",
    currency: "XOF",
    symbol: "CFA",
  },
  {
    name: "Sierra Leone",
    alpha2: "SL",
    alpha3: "SLE",
    currency: "SLL",
    symbol: "Le",
  },
  {
    name: "Slovakia",
    alpha2: "SK",
    alpha3: "SVK",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Slovenia",
    alpha2: "SI",
    alpha3: "SVN",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "South Africa",
    alpha2: "ZA",
    alpha3: "ZAF",
    currency: "ZAR",
    symbol: "R",
  },
  {
    name: "Spain",
    alpha2: "ES",
    alpha3: "ESP",
    currency: "EUR",
    symbol: "€",
  },
  {
    name: "Sweden",
    alpha2: "SE",
    alpha3: "SWE",
    currency: "SEK",
    symbol: "kr",
  },
  {
    name: "Switzerland",
    alpha2: "CH",
    alpha3: "CHE",
    currency: "CHF",
    symbol: "CHF",
  },
  {
    name: "Tanzania",
    alpha2: "TZ",
    alpha3: "TZA",
    currency: "TZS",
    symbol: "TSh",
  },
  {
    name: "Uganda",
    alpha2: "UG",
    alpha3: "UGA",
    currency: "UGX",
    symbol: "USh",
  },
  {
    name: "United Kingdom",
    alpha2: "GB",
    alpha3: "GBR",
    currency: "GBP",
    symbol: "£",
  },
  {
    name: "United States",
    alpha2: "US",
    alpha3: "USA",
    currency: "USD",
    symbol: "$",
  },
  {
    name: "Zambia",
    alpha2: "ZM",
    alpha3: "ZMB",
    currency: "ZMW",
    symbol: "ZK",
  },
];
