export const artist_countries_codes_currency = [
  {
    name: "Cameroon",
    alpha2: "CM",
    alpha3: "CMR",
    currency: "XAF",
    symbol: "FCFA",
  },
  { name: "Egypt", alpha2: "EG", alpha3: "EGY", currency: "EGP", symbol: "£" }, // Egyptian Pound
  { name: "Ghana", alpha2: "GH", alpha3: "GHA", currency: "GHS", symbol: "₵" },
  {
    name: "Côte d'Ivoire",
    alpha2: "CI",
    alpha3: "CIV",
    currency: "XOF",
    symbol: "CFA",
  },
  {
    name: "Kenya",
    alpha2: "KE",
    alpha3: "KEN",
    currency: "KES",
    symbol: "KSh",
  },
  {
    name: "Nigeria",
    alpha2: "NG",
    alpha3: "NGA",
    currency: "NGN",
    symbol: "₦",
  },
  {
    name: "Rwanda",
    alpha2: "RW",
    alpha3: "RWA",
    currency: "RWF",
    symbol: "FRw",
  },
  {
    name: "Senegal",
    alpha2: "SN",
    alpha3: "SEN",
    currency: "XOF",
    symbol: "CFA",
  },
  {
    name: "Sierra Leone",
    alpha2: "SL",
    alpha3: "SLE",
    currency: "SLL",
    symbol: "Le",
  },
  {
    name: "South Africa",
    alpha2: "ZA",
    alpha3: "ZAF",
    currency: "ZAR",
    symbol: "R",
  },
  {
    name: "Tanzania",
    alpha2: "TZ",
    alpha3: "TZA",
    currency: "TZS",
    symbol: "TSh",
  },
  {
    name: "Uganda",
    alpha2: "UG",
    alpha3: "UGA",
    currency: "UGX",
    symbol: "USh",
  },
  {
    name: "Zambia",
    alpha2: "ZM",
    alpha3: "ZMB",
    currency: "ZMW",
    symbol: "ZK",
  },
  {
    name: "Benin",
    alpha2: "BJ",
    alpha3: "BEN",
    currency: "XOF",
    symbol: "CFA",
  },
  {
    name: "Chad",
    alpha2: "TD",
    alpha3: "TCD",
    currency: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Ethiopia",
    alpha2: "ET",
    alpha3: "ETH",
    currency: "ETB",
    symbol: "Br",
  },
  {
    name: "Gabon",
    alpha2: "GA",
    alpha3: "GAB",
    currency: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    currency: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Congo",
    alpha2: "CG",
    alpha3: "COG",
    currency: "XAF",
    symbol: "FCFA",
  },
  {
    name: "Malawi",
    alpha2: "MW",
    alpha3: "MWI",
    currency: "MWK",
    symbol: "MK",
  },
  {
    name: "Botswana",
    alpha2: "BW",
    alpha3: "BWA",
    currency: "BWP",
    symbol: "P",
  },
  {
    name: "United States",
    alpha2: "US",
    alpha3: "USA",
    currency: "USD",
    symbol: "$",
  },
];
