export const artist_countries_codes_currency = [
  { name: "Cameroon", alpha2: "CM", alpha3: "CMR", currency: "XAF" },
  { name: "Egypt", alpha2: "EG", alpha3: "EGY", currency: "EGP" },
  { name: "Ghana", alpha2: "GH", alpha3: "GHA", currency: "GHS" },
  { name: "Côte d'Ivoire", alpha2: "CI", alpha3: "CIV", currency: "XOF" },
  { name: "Kenya", alpha2: "KE", alpha3: "KEN", currency: "KES" },
  { name: "Nigeria", alpha2: "NG", alpha3: "NGA", currency: "NGN" },
  { name: "Rwanda", alpha2: "RW", alpha3: "RWA", currency: "RWF" },
  { name: "Senegal", alpha2: "SN", alpha3: "SEN", currency: "XOF" },
  { name: "Sierra Leone", alpha2: "SL", alpha3: "SLE", currency: "SLL" },
  { name: "South Africa", alpha2: "ZA", alpha3: "ZAF", currency: "ZAR" },
  { name: "Tanzania", alpha2: "TZ", alpha3: "TZA", currency: "TZS" },
  { name: "Uganda", alpha2: "UG", alpha3: "UGA", currency: "UGX" },
  { name: "Zambia", alpha2: "ZM", alpha3: "ZMB", currency: "ZMW" },
  { name: "Benin", alpha2: "BJ", alpha3: "BEN", currency: "XOF" },
  { name: "Chad", alpha2: "TD", alpha3: "TCD", currency: "XAF" },
  { name: "Ethiopia", alpha2: "ET", alpha3: "ETH", currency: "ETB" },
  { name: "Gabon", alpha2: "GA", alpha3: "GAB", currency: "XAF" },
  {
    name: "Central African Republic",
    alpha2: "CF",
    alpha3: "CAF",
    currency: "XAF",
  },
  { name: "Congo", alpha2: "CG", alpha3: "COG", currency: "XAF" },
  { name: "Malawi", alpha2: "MW", alpha3: "MWI", currency: "MWK" },
  { name: "Botswana", alpha2: "BW", alpha3: "BWA", currency: "BWP" },
  { name: "United States", alpha2: "US", alpha3: "USA", currency: "USD" },
];
