export const country_codes = [
  { key: "AU", name: "Australia" },
  { key: "AT", name: "Austria" },
  { key: "BE", name: "Belgium" },
  { key: "BJ", name: "Benin" },
  { key: "BW", name: "Botswana" },
  { key: "CA", name: "Canada" },
  { key: "HR", name: "Croatia" },
  { key: "CY", name: "Cyprus" },
  { key: "CZ", name: "Czech Republic" },
  { key: "CI", name: "Côte d’Ivoire" },
  { key: "DK", name: "Denmark" },
  { key: "EG", name: "Egypt" },
  { key: "ET", name: "Ethiopia" },
  { key: "FI", name: "Finland" },
  { key: "FR", name: "France" },
  { key: "GM", name: "Gambia" },
  { key: "DE", name: "Germany" },
  { key: "GH", name: "Ghana" },
  { key: "GR", name: "Greece" },
  { key: "IS", name: "Iceland" },
  { key: "IE", name: "Ireland" },
  { key: "IT", name: "Italy" },
  { key: "JP", name: "Japan" },
  { key: "KE", name: "Kenya" },
  { key: "MG", name: "Madagascar" },
  { key: "MU", name: "Mauritius" },
  { key: "MC", name: "Monaco" },
  { key: "MA", name: "Morocco" },
  { key: "MZ", name: "Mozambique" },
  { key: "NA", name: "Namibia" },
  { key: "NL", name: "Netherlands" },
  { key: "NZ", name: "New Zealand" },
  { key: "NG", name: "Nigeria" },
  { key: "NO", name: "Norway" },
  { key: "PL", name: "Poland" },
  { key: "PT", name: "Portugal" },
  { key: "QA", name: "Qatar" },
  { key: "RW", name: "Rwanda" },
  { key: "SN", name: "Senegal" },
  { key: "SG", name: "Singapore" },
  { key: "ZA", name: "South Africa" },
  { key: "KR", name: "South Korea" },
  { key: "ES", name: "Spain" },
  { key: "SE", name: "Sweden" },
  { key: "CH", name: "Switzerland" },
  { key: "TZ", name: "Tanzania" },
  { key: "TR", name: "Turkey" },
  { key: "AE", name: "United Arab Emirates" },
  { key: "GB", name: "United Kingdom" },
  { key: "US", name: "United States" },
];
