import { US_NEXUS_THRESHOLD_LIST } from "@omenai/shared-types";

export const nexus_thresholds: US_NEXUS_THRESHOLD_LIST[] = [
  {
    state: "Alabama",
    stateCode: "AL",
    nexus_rule: {
      sales_threshold: 250000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_CALENDAR_YEAR",
      effective_date: "2018-10-01",
    },
  },
  {
    state: "Alaska",
    stateCode: "AK",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2020-01-01",
      note: "Transaction threshold removed as of January 1, 2025. No statewide sales tax; applies to participating local jurisdictions only",
    },
  },
  {
    state: "Arizona",
    stateCode: "AZ",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-10-01",
    },
  },
  {
    state: "Arkansas",
    stateCode: "AR",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-07-01",
    },
  },
  {
    state: "California",
    stateCode: "CA",
    nexus_rule: {
      sales_threshold: 500000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-04-01",
    },
  },
  {
    state: "Colorado",
    stateCode: "CO",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-06-01",
    },
  },
  {
    state: "Connecticut",
    stateCode: "CT",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_AND_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2018-12-01",
    },
  },
  {
    state: "Delaware",
    stateCode: "DE",
    nexus_rule: {
      sales_threshold: null,
      transactions_threshold: null,
      threshold_type: "NO_SALES_TAX",
      evaluation_period_type: null,
      effective_date: null,
    },
  },
  {
    state: "District of Columbia",
    stateCode: "DC",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-01-01",
    },
  },
  {
    state: "Florida",
    stateCode: "FL",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_CALENDAR_YEAR",
      effective_date: "2021-07-01",
    },
  },
  {
    state: "Georgia",
    stateCode: "GA",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-01-01",
    },
  },
  {
    state: "Hawaii",
    stateCode: "HI",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-07-01",
    },
  },
  {
    state: "Idaho",
    stateCode: "ID",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-06-01",
    },
  },
  {
    state: "Illinois",
    stateCode: "IL",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2018-10-01",
      note: "Transaction threshold will be removed January 1, 2026",
    },
  },
  {
    state: "Indiana",
    stateCode: "IN",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-10-01",
      note: "Transaction threshold removed as of January 1, 2024",
    },
  },
  {
    state: "Iowa",
    stateCode: "IA",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-01-01",
    },
  },
  {
    state: "Kansas",
    stateCode: "KS",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-10-01",
    },
  },
  {
    state: "Kentucky",
    stateCode: "KY",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-10-01",
    },
  },
  {
    state: "Louisiana",
    stateCode: "LA",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-07-01",
    },
  },
  {
    state: "Maine",
    stateCode: "ME",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-07-01",
    },
  },
  {
    state: "Maryland",
    stateCode: "MD",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-10-01",
    },
  },
  {
    state: "Massachusetts",
    stateCode: "MA",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-10-01",
    },
  },
  {
    state: "Michigan",
    stateCode: "MI",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_CALENDAR_YEAR",
      effective_date: "2018-10-01",
    },
  },
  {
    state: "Minnesota",
    stateCode: "MN",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2018-10-01",
    },
  },
  {
    state: "Mississippi",
    stateCode: "MS",
    nexus_rule: {
      sales_threshold: 250000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2018-09-01",
    },
  },
  {
    state: "Missouri",
    stateCode: "MO",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2023-01-01",
    },
  },
  {
    state: "Montana",
    stateCode: "MT",
    nexus_rule: {
      sales_threshold: null,
      transactions_threshold: null,
      threshold_type: "NO_SALES_TAX",
      evaluation_period_type: null,
      effective_date: null,
    },
  },
  {
    state: "Nebraska",
    stateCode: "NE",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-01-01",
    },
  },
  {
    state: "Nevada",
    stateCode: "NV",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-10-01",
    },
  },
  {
    state: "New Hampshire",
    stateCode: "NH",
    nexus_rule: {
      sales_threshold: null,
      transactions_threshold: null,
      threshold_type: "NO_SALES_TAX",
      evaluation_period_type: null,
      effective_date: null,
    },
  },
  {
    state: "New Jersey",
    stateCode: "NJ",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-10-01",
    },
  },
  {
    state: "New Mexico",
    stateCode: "NM",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_CALENDAR_YEAR",
      effective_date: "2019-07-01",
    },
  },
  {
    state: "New York",
    stateCode: "NY",
    nexus_rule: {
      sales_threshold: 500000,
      transactions_threshold: 100,
      threshold_type: "SALES_AND_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_4_QUARTERS",
      effective_date: "2019-06-24",
    },
  },
  {
    state: "North Carolina",
    stateCode: "NC",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-11-01",
    },
  },
  {
    state: "North Dakota",
    stateCode: "ND",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-10-01",
      note: "Transaction threshold removed July 1, 2019",
    },
  },
  {
    state: "Ohio",
    stateCode: "OH",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-08-01",
    },
  },
  {
    state: "Oklahoma",
    stateCode: "OK",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2018-11-01",
    },
  },
  {
    state: "Oregon",
    stateCode: "OR",
    nexus_rule: {
      sales_threshold: null,
      transactions_threshold: null,
      threshold_type: "NO_SALES_TAX",
      evaluation_period_type: null,
      effective_date: null,
    },
  },
  {
    state: "Pennsylvania",
    stateCode: "PA",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2019-07-01",
    },
  },
  {
    state: "Rhode Island",
    stateCode: "RI",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-07-01",
    },
  },
  {
    state: "South Carolina",
    stateCode: "SC",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-11-01",
    },
  },
  {
    state: "South Dakota",
    stateCode: "SD",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-11-01",
    },
  },
  {
    state: "Tennessee",
    stateCode: "TN",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2019-10-01",
    },
  },
  {
    state: "Texas",
    stateCode: "TX",
    nexus_rule: {
      sales_threshold: 500000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2019-10-01",
    },
  },
  {
    state: "Utah",
    stateCode: "UT",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-01-01",
      note: "Transaction threshold removed July 1, 2025",
    },
  },
  {
    state: "Vermont",
    stateCode: "VT",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_12_MONTHS",
      effective_date: "2018-07-01",
    },
  },
  {
    state: "Virginia",
    stateCode: "VA",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-07-01",
    },
  },
  {
    state: "Washington",
    stateCode: "WA",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-10-01",
    },
  },
  {
    state: "West Virginia",
    stateCode: "WV",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: 200,
      threshold_type: "SALES_OR_TRANSACTIONS",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-01-01",
    },
  },
  {
    state: "Wisconsin",
    stateCode: "WI",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2018-10-01",
    },
  },
  {
    state: "Wyoming",
    stateCode: "WY",
    nexus_rule: {
      sales_threshold: 100000,
      transactions_threshold: null,
      threshold_type: "SALES_ONLY",
      evaluation_period_type: "PREVIOUS_OR_CURRENT_CALENDAR_YEAR",
      effective_date: "2019-02-01",
      note: "Transaction threshold removed July 1, 2024",
    },
  },
];
