name: Build Check

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build
        env:
          TURBO_TELEMETRY_DISABLED: 1
          NEXT_TELEMETRY_DISABLED: 1
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          NEXT_PUBLIC_CONFIGCAT_STAGING_HIGH_RISK_SDK_KEY: ${{ secrets.NEXT_PUBLIC_CONFIGCAT_STAGING_HIGH_RISK_SDK_KEY }}
          NEXT_PUBLIC_CONFIGCAT_STAGING_LOW_RISK_SDK_KEY: ${{ secrets.NEXT_PUBLIC_CONFIGCAT_STAGING_LOW_RISK_SDK_KEY }}
          CONFIGCAT_BASIC_AUTH_USERNAME: ${{ secrets.CONFIGCAT_BASIC_AUTH_USERNAME }}
          CONFIGCAT_BASIC_AUTH_PASSWORD: ${{ secrets.CONFIGCAT_BASIC_AUTH_PASSWORD }}
          CONFIGCAT_BASIC_AUTHORIZATION_HEADER: ${{ secrets.CONFIGCAT_BASIC_AUTHORIZATION_HEADER }}
          NEXT_PUBLIC_CONFIGCAT_LOW_RISK_SDK_KEY: ${{ secrets.NEXT_PUBLIC_CONFIGCAT_LOW_RISK_SDK_KEY }}
          NEXT_PUBLIC_CONFIGCAT_HIGH_RISK_SDK_KEY: ${{ secrets.NEXT_PUBLIC_CONFIGCAT_HIGH_RISK_SDK_KEY }}
