name: Build Check

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build
        env:
          TURBO_TELEMETRY_DISABLED: 1
          NEXT_TELEMETRY_DISABLED: 1
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
