name: Unit Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

permissions:
  contents: read

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test
        env:
          TURBO_TELEMETRY_DISABLED: 1
          NODE_ENV: test
